global:
  scrape_interval: 15s  # How often to scrape targets by default.
  evaluation_interval: 15s  # How often to evaluate rules by default.

scrape_configs:
  - job_name: 'Concert Hall Booking System'  # Name of the job
    static_configs:
      - targets:
          - 'backend:8000'
